/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_java_liuyingtian_ivi_IVIService */

#ifndef _Included_com_java_liuyingtian_ivi_IVIService
#define _Included_com_java_liuyingtian_ivi_IVIService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_java_liuyingtian_ivi_IVIService
 * Method:    backend_thread
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_java_liuyingtian_ivi_IVIService_backend_1thread
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
